name = "ColabMPNN"
uuid = "434c8270-3839-45f3-8f5c-492a580b2514"
authors = ["Anton Oresten <anton.oresten42@gmail.com> and contributors"]
version = "0.0.2"

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
CondaPkg = "0.2.24"
PythonCall = "0.9.23"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
