name: CI
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
          - 'nightly'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1

      # Custom step to build PyCall
      - name: Build PyCall
        run: julia --project=@. -e 'using Pkg; Pkg.build("PyCall")'

      # If you need to install Conda and/or other packages, add them here
      - name: Install Conda and Python dependencies
        run: |
          julia --project=@. -e 'using Pkg; Pkg.add("Conda"); using Conda; Conda.pip_interop(true); Conda.pip("install", "git+https://github.com/sokrypton/ColabDesign.git@v1.1.1")'

      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
